/* Base de alimentos: kcal por 100 g (o por 100 ml en bebidas).
   p = porciones habituales [etiqueta, gramos]. La primera es la que sale por defecto. */
const CATEGORIAS = [
  ["fruta",    "Frutas",            "🍎"],
  ["verdura",  "Verduras y patata", "🥦"],
  ["cereal",   "Pan, arroz y pasta","🍞"],
  ["lacteo",   "Lácteos y huevos",  "🥛"],
  ["carne",    "Carnes y embutidos","🍗"],
  ["pescado",  "Pescados y marisco","🐟"],
  ["legumbre", "Legumbres",         "🫘"],
  ["fruto",    "Frutos secos",      "🥜"],
  ["plato",    "Platos preparados", "🍲"],
  ["bebida",   "Bebidas",           "☕"],
  ["grasa",    "Aceites y salsas",  "🫒"],
  ["dulce",    "Dulces y aperitivos","🍫"],
  ["chileno",  "De Chile",          "🇨🇱"]
];

const ALIMENTOS = [
  // ---------- Frutas ----------
  {n:"Manzana", c:"fruta", k:52, p:[["1 unidad",180],["media unidad",90]]},
  {n:"Plátano", c:"fruta", k:89, p:[["1 unidad",120],["media unidad",60]]},
  {n:"Naranja", c:"fruta", k:47, p:[["1 unidad",180]]},
  {n:"Mandarina", c:"fruta", k:53, p:[["1 unidad",80],["2 unidades",160]]},
  {n:"Pera", c:"fruta", k:57, p:[["1 unidad",170]]},
  {n:"Uvas", c:"fruta", k:69, p:[["1 puñado",100]]},
  {n:"Fresas", c:"fruta", k:32, p:[["1 plato",150]]},
  {n:"Sandía", c:"fruta", k:30, p:[["1 rodaja",200]]},
  {n:"Melón", c:"fruta", k:34, p:[["1 rodaja",200]]},
  {n:"Kiwi", c:"fruta", k:61, p:[["1 unidad",75]]},
  {n:"Melocotón", c:"fruta", k:39, p:[["1 unidad",150]]},
  {n:"Piña", c:"fruta", k:50, p:[["1 rodaja",100]]},
  {n:"Ciruela", c:"fruta", k:46, p:[["1 unidad",60]]},
  {n:"Cerezas", c:"fruta", k:63, p:[["1 puñado",100]]},
  {n:"Aguacate", c:"fruta", k:160, p:[["medio",100],["1 unidad",200]]},
  {n:"Higos", c:"fruta", k:74, p:[["1 unidad",50]]},
  {n:"Granada", c:"fruta", k:83, p:[["1 unidad",200]]},
  {n:"Macedonia de frutas", c:"fruta", k:55, p:[["1 bol",200]]},

  // ---------- Verduras ----------
  {n:"Lechuga", c:"verdura", k:15, p:[["1 plato",100]]},
  {n:"Ensalada mixta (sin aliñar)", c:"verdura", k:25, p:[["1 plato",200]]},
  {n:"Tomate", c:"verdura", k:18, p:[["1 unidad",120]]},
  {n:"Pepino", c:"verdura", k:15, p:[["medio",100]]},
  {n:"Zanahoria", c:"verdura", k:41, p:[["1 unidad",80]]},
  {n:"Cebolla", c:"verdura", k:40, p:[["media",70]]},
  {n:"Pimiento", c:"verdura", k:26, p:[["1 unidad",120]]},
  {n:"Calabacín", c:"verdura", k:17, p:[["1 unidad",200]]},
  {n:"Berenjena", c:"verdura", k:25, p:[["media",120]]},
  {n:"Brócoli", c:"verdura", k:34, p:[["1 plato",200]]},
  {n:"Judías verdes", c:"verdura", k:31, p:[["1 plato",200]]},
  {n:"Espinacas", c:"verdura", k:23, p:[["1 plato",200]]},
  {n:"Acelgas", c:"verdura", k:19, p:[["1 plato",200]]},
  {n:"Champiñones", c:"verdura", k:22, p:[["1 plato",150]]},
  {n:"Alcachofas", c:"verdura", k:47, p:[["1 plato",200]]},
  {n:"Espárragos", c:"verdura", k:20, p:[["1 ración",125]]},
  {n:"Guisantes", c:"verdura", k:81, p:[["1 plato",200]]},
  {n:"Coliflor", c:"verdura", k:25, p:[["1 plato",200]]},
  {n:"Calabaza", c:"verdura", k:26, p:[["1 plato",200]]},
  {n:"Puerro", c:"verdura", k:61, p:[["1 unidad",100]]},
  {n:"Pisto de verduras", c:"verdura", k:80, p:[["1 plato",250]]},
  {n:"Patata cocida", c:"verdura", k:86, p:[["1 unidad",150]]},
  {n:"Patata asada", c:"verdura", k:93, p:[["1 unidad",150]]},
  {n:"Patatas fritas", c:"verdura", k:312, p:[["1 ración",150],["media ración",75]]},

  // ---------- Cereales, pan ----------
  {n:"Pan blanco (barra)", c:"cereal", k:265, p:[["1 trozo",50],["media barra",100]]},
  {n:"Pan integral", c:"cereal", k:247, p:[["1 trozo",50]]},
  {n:"Pan de molde", c:"cereal", k:265, p:[["1 rebanada",28],["2 rebanadas",56]]},
  {n:"Pan tostado (biscote)", c:"cereal", k:380, p:[["1 unidad",8],["2 unidades",16]]},
  {n:"Picos / colines", c:"cereal", k:430, p:[["1 puñado",25]]},
  {n:"Arroz cocido", c:"cereal", k:130, p:[["1 plato",200],["medio plato",100]]},
  {n:"Pasta cocida", c:"cereal", k:158, p:[["1 plato",200],["medio plato",100]]},
  {n:"Cereales de desayuno", c:"cereal", k:380, p:[["1 tazón",40]]},
  {n:"Avena en copos", c:"cereal", k:389, p:[["1 puñado",40]]},
  {n:"Galletas María", c:"cereal", k:430, p:[["1 unidad",6],["4 unidades",24]]},
  {n:"Croissant", c:"cereal", k:406, p:[["1 unidad",60]]},
  {n:"Magdalena", c:"cereal", k:400, p:[["1 unidad",40]]},
  {n:"Cuscús cocido", c:"cereal", k:112, p:[["1 plato",200]]},
  {n:"Quinoa cocida", c:"cereal", k:120, p:[["1 plato",200]]},
  {n:"Tortilla de trigo (wrap)", c:"cereal", k:300, p:[["1 unidad",45]]},

  // ---------- Lácteos y huevos ----------
  {n:"Leche entera", c:"lacteo", k:61, p:[["1 vaso",250],["media taza",125]]},
  {n:"Leche semidesnatada", c:"lacteo", k:46, p:[["1 vaso",250]]},
  {n:"Leche desnatada", c:"lacteo", k:34, p:[["1 vaso",250]]},
  {n:"Yogur natural", c:"lacteo", k:61, p:[["1 unidad",125]]},
  {n:"Yogur natural desnatado", c:"lacteo", k:40, p:[["1 unidad",125]]},
  {n:"Yogur griego", c:"lacteo", k:115, p:[["1 unidad",125]]},
  {n:"Yogur de sabores", c:"lacteo", k:85, p:[["1 unidad",125]]},
  {n:"Queso fresco", c:"lacteo", k:96, p:[["1 tarrina",60]]},
  {n:"Queso curado", c:"lacteo", k:390, p:[["1 loncha",25],["1 ración",50]]},
  {n:"Queso semicurado", c:"lacteo", k:350, p:[["1 loncha",25]]},
  {n:"Queso de untar", c:"lacteo", k:250, p:[["1 cucharada",15]]},
  {n:"Mozzarella", c:"lacteo", k:280, p:[["1 ración",50]]},
  {n:"Nata líquida", c:"lacteo", k:340, p:[["1 cucharada",15]]},
  {n:"Mantequilla", c:"lacteo", k:717, p:[["1 porción",10]]},
  {n:"Natillas / flan", c:"lacteo", k:125, p:[["1 unidad",125]]},
  {n:"Cuajada", c:"lacteo", k:100, p:[["1 unidad",125]]},
  {n:"Helado", c:"lacteo", k:200, p:[["1 bola",60],["1 tarrina",100]]},
  {n:"Huevo", c:"lacteo", k:143, p:[["1 unidad",55],["2 unidades",110]]},
  {n:"Huevo frito", c:"lacteo", k:200, p:[["1 unidad",60]]},
  {n:"Tortilla francesa", c:"lacteo", k:170, p:[["de 2 huevos",120]]},
  {n:"Tortilla de patata", c:"lacteo", k:220, p:[["1 pincho",120],["1 ración grande",200]]},

  // ---------- Carnes ----------
  {n:"Pechuga de pollo", c:"carne", k:165, p:[["1 filete",150]]},
  {n:"Muslo de pollo", c:"carne", k:190, p:[["1 unidad",150]]},
  {n:"Pollo asado", c:"carne", k:200, p:[["1 ración",200]]},
  {n:"Pavo (pechuga)", c:"carne", k:135, p:[["1 filete",150]]},
  {n:"Ternera", c:"carne", k:190, p:[["1 filete",150]]},
  {n:"Lomo de cerdo", c:"carne", k:195, p:[["1 filete",150]]},
  {n:"Chuleta de cerdo", c:"carne", k:240, p:[["1 unidad",180]]},
  {n:"Cordero", c:"carne", k:250, p:[["1 ración",150]]},
  {n:"Hamburguesa de ternera", c:"carne", k:250, p:[["1 unidad",120]]},
  {n:"Albóndigas", c:"carne", k:220, p:[["1 ración",200]]},
  {n:"Salchichas", c:"carne", k:300, p:[["1 unidad",40],["2 unidades",80]]},
  {n:"Jamón serrano", c:"carne", k:240, p:[["1 loncha",20],["1 ración",50]]},
  {n:"Jamón cocido / york", c:"carne", k:110, p:[["1 loncha",25],["2 lonchas",50]]},
  {n:"Pavo en lonchas", c:"carne", k:100, p:[["2 lonchas",50]]},
  {n:"Chorizo", c:"carne", k:450, p:[["1 rodaja",10],["4 rodajas",40]]},
  {n:"Salchichón", c:"carne", k:400, p:[["4 rodajas",40]]},
  {n:"Bacon", c:"carne", k:500, p:[["1 loncha",15]]},
  {n:"Morcilla", c:"carne", k:380, p:[["1 rodaja",40]]},

  // ---------- Pescados ----------
  {n:"Merluza", c:"pescado", k:90, p:[["1 filete",150]]},
  {n:"Bacalao", c:"pescado", k:82, p:[["1 lomo",150]]},
  {n:"Lenguado", c:"pescado", k:85, p:[["1 unidad",150]]},
  {n:"Dorada", c:"pescado", k:96, p:[["1 unidad",200]]},
  {n:"Lubina", c:"pescado", k:97, p:[["1 unidad",200]]},
  {n:"Salmón", c:"pescado", k:208, p:[["1 lomo",150]]},
  {n:"Atún fresco", c:"pescado", k:130, p:[["1 filete",150]]},
  {n:"Atún en lata al natural", c:"pescado", k:110, p:[["1 lata",55]]},
  {n:"Atún en lata en aceite", c:"pescado", k:190, p:[["1 lata",55]]},
  {n:"Sardinas", c:"pescado", k:208, p:[["1 ración",150]]},
  {n:"Boquerones", c:"pescado", k:110, p:[["1 ración",150]]},
  {n:"Gambas / langostinos", c:"pescado", k:85, p:[["1 ración",150]]},
  {n:"Mejillones", c:"pescado", k:86, p:[["1 ración",150]]},
  {n:"Calamares a la plancha", c:"pescado", k:92, p:[["1 ración",150]]},
  {n:"Calamares fritos", c:"pescado", k:220, p:[["1 ración",150]]},
  {n:"Pulpo", c:"pescado", k:82, p:[["1 ración",150]]},
  {n:"Palitos de cangrejo", c:"pescado", k:95, p:[["1 unidad",20]]},
  {n:"Varitas de merluza", c:"pescado", k:220, p:[["1 unidad",30],["3 unidades",90]]},

  // ---------- Legumbres ----------
  {n:"Lentejas cocidas", c:"legumbre", k:116, p:[["1 plato",250]]},
  {n:"Lentejas con chorizo", c:"legumbre", k:150, p:[["1 plato",250]]},
  {n:"Garbanzos cocidos", c:"legumbre", k:164, p:[["1 plato",250]]},
  {n:"Cocido / potaje", c:"legumbre", k:150, p:[["1 plato",300]]},
  {n:"Alubias cocidas", c:"legumbre", k:125, p:[["1 plato",250]]},
  {n:"Hummus", c:"legumbre", k:170, p:[["2 cucharadas",40]]},
  {n:"Tofu", c:"legumbre", k:145, p:[["1 ración",100]]},

  // ---------- Frutos secos ----------
  {n:"Almendras", c:"fruto", k:575, p:[["1 puñado",25],["medio puñado",12]]},
  {n:"Nueces", c:"fruto", k:654, p:[["1 unidad",5],["1 puñado",25]]},
  {n:"Avellanas", c:"fruto", k:628, p:[["1 puñado",25]]},
  {n:"Pistachos", c:"fruto", k:560, p:[["1 puñado",25]]},
  {n:"Cacahuetes", c:"fruto", k:567, p:[["1 puñado",25]]},
  {n:"Anacardos", c:"fruto", k:553, p:[["1 puñado",25]]},
  {n:"Pipas de girasol", c:"fruto", k:584, p:[["1 puñado",25]]},
  {n:"Dátiles", c:"fruto", k:282, p:[["1 unidad",8]]},
  {n:"Pasas", c:"fruto", k:299, p:[["1 puñado",25]]},

  // ---------- Platos preparados ----------
  {n:"Pizza", c:"plato", k:266, p:[["1 porción",100],["media pizza",200],["1 pizza",400]]},
  {n:"Paella", c:"plato", k:160, p:[["1 plato",300]]},
  {n:"Macarrones con tomate", c:"plato", k:160, p:[["1 plato",300]]},
  {n:"Espaguetis a la boloñesa", c:"plato", k:180, p:[["1 plato",300]]},
  {n:"Lasaña", c:"plato", k:180, p:[["1 ración",300]]},
  {n:"Canelones", c:"plato", k:170, p:[["1 ración",250]]},
  {n:"Arroz a la cubana", c:"plato", k:200, p:[["1 plato",300]]},
  {n:"Sopa de fideos", c:"plato", k:40, p:[["1 plato",250]]},
  {n:"Crema de verduras", c:"plato", k:50, p:[["1 plato",250]]},
  {n:"Gazpacho", c:"plato", k:50, p:[["1 vaso",250]]},
  {n:"Puré de patata", c:"plato", k:90, p:[["1 plato",250]]},
  {n:"Ensaladilla rusa", c:"plato", k:200, p:[["1 ración",150]]},
  {n:"Croquetas", c:"plato", k:250, p:[["1 unidad",30],["3 unidades",90]]},
  {n:"Empanadillas", c:"plato", k:280, p:[["1 unidad",50]]},
  {n:"Empanada", c:"plato", k:250, p:[["1 porción",100]]},
  {n:"Sándwich mixto", c:"plato", k:280, p:[["1 unidad",130]]},
  {n:"Bocadillo de jamón", c:"plato", k:250, p:[["1 unidad",150],["medio",75]]},
  {n:"Hamburguesa completa", c:"plato", k:260, p:[["1 unidad",220]]},
  {n:"Perrito caliente", c:"plato", k:250, p:[["1 unidad",150]]},
  {n:"Kebab", c:"plato", k:215, p:[["1 unidad",350]]},
  {n:"Sushi", c:"plato", k:130, p:[["1 pieza",25],["8 piezas",200]]},
  {n:"Revuelto de setas", c:"plato", k:130, p:[["1 ración",200]]},

  // ---------- Bebidas ----------
  {n:"Agua", c:"bebida", k:0, p:[["1 vaso",250]]},
  {n:"Café solo", c:"bebida", k:2, p:[["1 taza",50]]},
  {n:"Café con leche", c:"bebida", k:60, p:[["1 taza",150]]},
  {n:"Cortado", c:"bebida", k:35, p:[["1 taza",80]]},
  {n:"Té o infusión", c:"bebida", k:1, p:[["1 taza",250]]},
  {n:"Colacao / chocolate a la taza", c:"bebida", k:120, p:[["1 taza",250]]},
  {n:"Zumo de naranja natural", c:"bebida", k:45, p:[["1 vaso",200]]},
  {n:"Zumo envasado", c:"bebida", k:45, p:[["1 vaso",200],["1 brik",330]]},
  {n:"Refresco de cola", c:"bebida", k:42, p:[["1 lata",330],["1 vaso",250]]},
  {n:"Refresco light o zero", c:"bebida", k:0, p:[["1 lata",330]]},
  {n:"Cerveza", c:"bebida", k:43, p:[["1 caña",200],["1 botellín",250],["1 tercio",330]]},
  {n:"Cerveza sin alcohol", c:"bebida", k:25, p:[["1 botellín",250]]},
  {n:"Vino tinto", c:"bebida", k:85, p:[["1 copa",120]]},
  {n:"Vino blanco", c:"bebida", k:82, p:[["1 copa",120]]},
  {n:"Cava", c:"bebida", k:80, p:[["1 copa",120]]},
  {n:"Vermut", c:"bebida", k:140, p:[["1 copa",100]]},
  {n:"Copa (whisky, ginebra, ron)", c:"bebida", k:230, p:[["1 copa",60]]},
  {n:"Sidra", c:"bebida", k:45, p:[["1 vaso",200]]},
  {n:"Bebida de avena", c:"bebida", k:45, p:[["1 vaso",250]]},
  {n:"Bebida de almendra", c:"bebida", k:22, p:[["1 vaso",250]]},
  {n:"Batido de chocolate", c:"bebida", k:80, p:[["1 brik",200]]},

  // ---------- Aceites y salsas ----------
  {n:"Aceite de oliva", c:"grasa", k:884, p:[["1 chorrito",5],["1 cucharada",10],["2 cucharadas",20]]},
  {n:"Aceite de girasol", c:"grasa", k:884, p:[["1 cucharada",10]]},
  {n:"Mayonesa", c:"grasa", k:680, p:[["1 cucharada",15]]},
  {n:"Alioli", c:"grasa", k:600, p:[["1 cucharada",15]]},
  {n:"Kétchup", c:"grasa", k:110, p:[["1 cucharada",15]]},
  {n:"Tomate frito", c:"grasa", k:90, p:[["2 cucharadas",40]]},
  {n:"Mostaza", c:"grasa", k:66, p:[["1 cucharada",15]]},
  {n:"Vinagre", c:"grasa", k:20, p:[["1 cucharada",15]]},
  {n:"Azúcar", c:"grasa", k:400, p:[["1 cucharadita",5],["1 sobre",8]]},
  {n:"Miel", c:"grasa", k:304, p:[["1 cucharada",20]]},
  {n:"Mermelada", c:"grasa", k:250, p:[["1 cucharada",20]]},

  // ---------- Dulces y aperitivos ----------
  {n:"Chocolate con leche", c:"dulce", k:535, p:[["1 onza",10],["3 onzas",30]]},
  {n:"Chocolate negro", c:"dulce", k:550, p:[["1 onza",10]]},
  {n:"Bombón", c:"dulce", k:500, p:[["1 unidad",12]]},
  {n:"Galletas tipo digestive", c:"dulce", k:480, p:[["1 unidad",15],["2 unidades",30]]},
  {n:"Donut", c:"dulce", k:450, p:[["1 unidad",60]]},
  {n:"Bizcocho casero", c:"dulce", k:380, p:[["1 porción",60]]},
  {n:"Tarta de queso", c:"dulce", k:320, p:[["1 porción",100]]},
  {n:"Churros", c:"dulce", k:350, p:[["1 unidad",25],["1 ración",100]]},
  {n:"Palmera de chocolate", c:"dulce", k:450, p:[["1 unidad",80]]},
  {n:"Turrón", c:"dulce", k:500, p:[["1 trozo",30]]},
  {n:"Caramelos", c:"dulce", k:390, p:[["1 unidad",5]]},
  {n:"Patatas fritas de bolsa", c:"dulce", k:536, p:[["1 puñado",25],["1 bolsa pequeña",45]]},
  {n:"Aceitunas", c:"dulce", k:145, p:[["6 unidades",30]]},
  {n:"Palomitas", c:"dulce", k:400, p:[["1 bol",30]]},
  // ---------- de Chile ----------
  {n:"Marraqueta", c:"chileno", k:265, p:[["1 unidad",100],["media",50]]},
  {n:"Hallulla", c:"chileno", k:290, p:[["1 unidad",90]]},
  {n:"Pan amasado", c:"chileno", k:280, p:[["1 unidad",100]]},
  {n:"Palta", c:"chileno", k:160, p:[["media",100],["1 unidad",200]]},
  {n:"Palta molida (para el pan)", c:"chileno", k:170, p:[["1 cucharada",25]]},
  {n:"Quesillo", c:"chileno", k:98, p:[["1 tarrina",80],["1 trozo",40]]},
  {n:"Manjar", c:"chileno", k:315, p:[["1 cucharada",20]]},
  {n:"Pebre", c:"chileno", k:60, p:[["2 cucharadas",40]]},
  {n:"Ensalada chilena", c:"chileno", k:45, p:[["1 plato",200]]},
  {n:"Cazuela de vacuno", c:"chileno", k:110, p:[["1 plato",400]]},
  {n:"Cazuela de pollo", c:"chileno", k:95, p:[["1 plato",400]]},
  {n:"Charquicán", c:"chileno", k:110, p:[["1 plato",350]]},
  {n:"Porotos granados", c:"chileno", k:130, p:[["1 plato",350]]},
  {n:"Porotos con riendas", c:"chileno", k:145, p:[["1 plato",350]]},
  {n:"Tomaticán", c:"chileno", k:120, p:[["1 plato",350]]},
  {n:"Pastel de choclo", c:"chileno", k:150, p:[["1 porción",350]]},
  {n:"Humita", c:"chileno", k:170, p:[["1 unidad",180]]},
  {n:"Empanada de pino", c:"chileno", k:280, p:[["1 unidad",250],["media",125]]},
  {n:"Empanada de queso", c:"chileno", k:320, p:[["1 unidad",120]]},
  {n:"Sopaipilla", c:"chileno", k:340, p:[["1 unidad",50],["2 unidades",100]]},
  {n:"Sopaipilla pasada", c:"chileno", k:300, p:[["1 unidad",70]]},
  {n:"Completo", c:"chileno", k:270, p:[["1 unidad",250]]},
  {n:"Churrasco (sándwich)", c:"chileno", k:250, p:[["1 unidad",250]]},
  {n:"Barros Luco", c:"chileno", k:270, p:[["1 unidad",250]]},
  {n:"Chorrillana", c:"chileno", k:230, p:[["1 ración",300]]},
  {n:"Longaniza", c:"chileno", k:380, p:[["1 unidad",80]]},
  {n:"Prieta", c:"chileno", k:370, p:[["1 unidad",100]]},
  {n:"Arrollado de huaso", c:"chileno", k:300, p:[["1 ración",100]]},
  {n:"Merluza austral", c:"chileno", k:90, p:[["1 filete",180]]},
  {n:"Reineta", c:"chileno", k:95, p:[["1 filete",180]]},
  {n:"Congrio", c:"chileno", k:100, p:[["1 filete",180]]},
  {n:"Machas a la parmesana", c:"chileno", k:190, p:[["1 ración",200]]},
  {n:"Mote con huesillo", c:"chileno", k:85, p:[["1 vaso",300]]},
  {n:"Chirimoya", c:"chileno", k:75, p:[["1 unidad",200]]},
  {n:"Lúcuma", c:"chileno", k:99, p:[["1 unidad",100]]},
  {n:"Alfajor", c:"chileno", k:420, p:[["1 unidad",40]]},
  {n:"Berlín", c:"chileno", k:390, p:[["1 unidad",90]]},
  {n:"Calzones rotos", c:"chileno", k:400, p:[["1 unidad",30]]},
  {n:"Té con leche", c:"chileno", k:45, p:[["1 taza",250]]},
  {n:"Milcao", c:"chileno", k:250, p:[["1 unidad",100]]},
  {n:"Charqui", c:"chileno", k:410, p:[["1 puñado",30]]},
  {n:"Merkén", c:"chileno", k:280, p:[["1 cucharadita",2]]}
];
