/* Ingredientes con nombre y producto chileno habitual.
   kcal y prot son SIEMPRE por 100 g.
   c = cantidad por porción · g = gramos que pesa una unidad de "u" (para las cuentas). */

const INGREDIENTES = {
  // ---------- lácteos y huevos ----------
  "yogur-griego":   {n:"Yogur griego natural", cat:"lacteo", u:"g", c:170, g:1, kcal:97, prot:9,
                     prod:"Soprole Protein, Colun Protein o Quillayes griego sin azúcar",
                     corto:"yogur", claves:["yogur","yogurt","griego","proteina","proteico"]},
  "yogur-natural":  {n:"Yogur natural", cat:"lacteo", u:"g", c:170, g:1, kcal:61, prot:3.5,
                     prod:"Colun o Soprole natural sin azúcar", corto:"yogur", claves:["yogur","yogurt","natural"]},
  "leche":          {n:"Leche descremada", cat:"lacteo", u:"ml", c:200, g:1, kcal:35, prot:3.4,
                     prod:"Colun, Soprole o Loncoleche descremada", corto:"leche", claves:["leche"]},
  "quesillo":       {n:"Quesillo", cat:"lacteo", u:"g", c:80, g:1, kcal:98, prot:12,
                     prod:"Quesillo Colun o Quillayes", claves:["quesillo","queso fresco","queso"]},
  "queso-mantecoso":{n:"Queso mantecoso", cat:"lacteo", u:"g", c:30, g:1, kcal:350, prot:24,
                     prod:"Colun o Chevrita mantecoso", corto:"queso", claves:["queso","mantecoso","gauda"]},
  "huevo":          {n:"Huevo", cat:"proteina", u:"unidad", c:2, g:55, kcal:143, prot:12.6,
                     prod:"Huevos de gallina libre, tamaño grande", claves:["huevo","huevos","revuelto","tortilla"]},
  "mantequilla":    {n:"Mantequilla", cat:"grasa", u:"cdta", c:1, g:5, kcal:717, prot:0.9,
                     prod:"Soprole o Colun con sal", corto:"mantequilla", claves:["mantequilla"]},

  // ---------- proteínas ----------
  "atun-agua":      {n:"Atún al agua", cat:"proteina", u:"g", c:120, g:1, kcal:110, prot:24,
                     prod:"San José, Robinson Crusoe o Colonial, lata al agua (escurrida)",
                     corto:"atún", claves:["atun","atún","lata"]},
  "pollo-pechuga":  {n:"Pechuga de pollo", cat:"proteina", u:"g", c:150, g:1, kcal:165, prot:31,
                     prod:"Pechuga Ariztía o Súper Pollo, sin piel", corto:"pollo", claves:["pollo","pechuga"]},
  "pollo-trutro":   {n:"Trutro de pollo", cat:"proteina", u:"g", c:180, g:1, kcal:190, prot:26,
                     prod:"Trutro corto Ariztía o Súper Pollo", corto:"pollo", claves:["pollo","trutro","muslo","cazuela"]},
  "carne-molida":   {n:"Carne molida de vacuno", cat:"proteina", u:"g", c:120, g:1, kcal:215, prot:26,
                     prod:"Posta molida (5% grasa) de la carnicería o Lider", corto:"carne", claves:["carne","molida","vacuno","charquican","pastel de choclo"]},
  "salmon":         {n:"Salmón", cat:"proteina", u:"g", c:150, g:1, kcal:208, prot:22,
                     prod:"Filete de salmón fresco o congelado (Multiexport, Camanchaca)", corto:"salmón", claves:["salmon","salmón","pescado"]},
  "merluza":        {n:"Merluza austral", cat:"proteina", u:"g", c:180, g:1, kcal:90, prot:18,
                     prod:"Filete de merluza congelado (Pacific Star o de la feria)", corto:"merluza", claves:["merluza","pescado","pescada"]},
  "jamon-pavo":     {n:"Jamón de pavo", cat:"proteina", u:"g", c:60, g:1, kcal:110, prot:17,
                     prod:"PF, San Jorge o La Preferida, bajo en sodio", corto:"pavo", claves:["jamon","jamón","pavo","fiambre"]},

  // ---------- legumbres y granos ----------
  "porotos":        {n:"Porotos cocidos", cat:"legumbre", u:"g", c:180, g:1, kcal:125, prot:8,
                     prod:"Porotos burros o negros, a granel o en conserva Wasil", corto:"porotos", claves:["porotos","poroto","frijol","legumbre"]},
  "garbanzos":      {n:"Garbanzos cocidos", cat:"legumbre", u:"g", c:180, g:1, kcal:164, prot:9,
                     prod:"Garbanzos a granel o en conserva Wasil", claves:["garbanzo","garbanzos","legumbre"]},
  "lentejas":       {n:"Lentejas cocidas", cat:"legumbre", u:"g", c:200, g:1, kcal:116, prot:9,
                     prod:"Lentejas chilenas a granel", claves:["lenteja","lentejas","legumbre"]},
  "quinoa":         {n:"Quinoa cocida", cat:"carbo", u:"g", c:150, g:1, kcal:120, prot:4.4,
                     prod:"Quinoa Andina o a granel", corto:"quinoa", claves:["quinoa","quinua"]},
  "arroz":          {n:"Arroz cocido", cat:"carbo", u:"g", c:150, g:1, kcal:130, prot:2.7,
                     prod:"Arroz grado 1 Tucapel o Miraflores", corto:"arroz", claves:["arroz"]},
  "fideos":         {n:"Fideos cocidos", cat:"carbo", u:"g", c:180, g:1, kcal:158, prot:5.8,
                     prod:"Fideos Carozzi o Lucchetti", corto:"fideos", claves:["fideo","fideos","pasta","tallarines"]},
  "avena":          {n:"Avena", cat:"carbo", u:"g", c:40, g:1, kcal:389, prot:13,
                     prod:"Avena instantánea Quaker", claves:["avena"]},
  "mote":           {n:"Mote de trigo cocido", cat:"carbo", u:"g", c:150, g:1, kcal:120, prot:3.5,
                     prod:"Mote pelado, en bolsa", claves:["mote","trigo"]},
  "papa":           {n:"Papas", cat:"carbo", u:"g", c:200, g:1, kcal:86, prot:2,
                     prod:"Papa cardinal o desirée, de la feria", corto:"papas", claves:["papa","papas","pure","puré"]},
  "choclo":         {n:"Choclo desgranado", cat:"verdura", u:"g", c:120, g:1, kcal:96, prot:3.4,
                     prod:"Choclo fresco o congelado (Bonduelle, Wasil)", claves:["choclo","maiz","maíz","humita","pastel de choclo"]},
  "camote":         {n:"Camote", cat:"carbo", u:"g", c:180, g:1, kcal:86, prot:1.6,
                     prod:"Camote de la feria", claves:["camote","batata"]},

  // ---------- pan ----------
  "marraqueta":     {n:"Marraqueta", cat:"carbo", u:"unidad", c:1, g:100, kcal:265, prot:8,
                     prod:"Marraqueta del día, de la panadería", claves:["marraqueta","pan","hallulla"]},
  "pan-integral":   {n:"Pan integral de molde", cat:"carbo", u:"unidad", c:2, g:30, kcal:247, prot:10,
                     prod:"Ideal o Bimbo integral", corto:"pan integral", claves:["pan","integral","tostada","molde"]},
  "pan-pita":       {n:"Pan pita", cat:"carbo", u:"unidad", c:1, g:60, kcal:275, prot:9,
                     prod:"Pan pita Ideal", claves:["pita","wrap","tortilla","sandwich"]},
  "galleta-arroz":  {n:"Galletas de arroz", cat:"carbo", u:"unidad", c:3, g:8, kcal:375, prot:7.5,
                     prod:"Galletas de arroz Vivo o Quaker", corto:"galletas de arroz", claves:["galleta","galletas de arroz"]},

  // ---------- verduras ----------
  "tomate":         {n:"Tomate", cat:"verdura", u:"unidad", c:1, g:120, kcal:18, prot:0.9,
                     prod:"Tomate limachino de la feria", claves:["tomate"]},
  "lechuga":        {n:"Lechuga", cat:"verdura", u:"g", c:80, g:1, kcal:15, prot:1.4,
                     prod:"Lechuga costina o escarola", claves:["lechuga"]},
  "cebolla":        {n:"Cebolla", cat:"verdura", u:"unidad", c:0.5, g:120, kcal:40, prot:1.1,
                     prod:"Cebolla nueva o morada para ensaladas", claves:["cebolla"]},
  "palta":          {n:"Palta", cat:"grasa", u:"unidad", c:0.5, g:150, kcal:160, prot:2,
                     prod:"Palta Hass, madura", claves:["palta","aguacate"]},
  "zanahoria":      {n:"Zanahoria", cat:"verdura", u:"unidad", c:1, g:80, kcal:41, prot:0.9,
                     prod:"Zanahoria de la feria", claves:["zanahoria"]},
  "zapallo-italiano":{n:"Zapallo italiano", cat:"verdura", u:"unidad", c:1, g:200, kcal:17, prot:1.2,
                     prod:"Zapallo italiano de la feria", claves:["zapallo","italiano","zucchini","calabacin"]},
  "zapallo":        {n:"Zapallo camote", cat:"verdura", u:"g", c:200, g:1, kcal:26, prot:1,
                     prod:"Zapallo camote en trozo", claves:["zapallo","calabaza","charquican"]},
  "poroto-verde":   {n:"Porotos verdes", cat:"verdura", u:"g", c:150, g:1, kcal:31, prot:1.8,
                     prod:"Porotos verdes frescos o congelados", corto:"porotos verdes", claves:["poroto verde","porotos verdes","judia"]},
  "betarraga":      {n:"Betarraga cocida", cat:"verdura", u:"g", c:120, g:1, kcal:43, prot:1.6,
                     prod:"Betarraga de la feria", claves:["betarraga","remolacha"]},
  "apio":           {n:"Apio", cat:"verdura", u:"g", c:60, g:1, kcal:16, prot:0.7,
                     prod:"Apio fresco", claves:["apio"]},
  "pimenton":       {n:"Pimentón", cat:"verdura", u:"unidad", c:0.5, g:150, kcal:26, prot:1,
                     prod:"Pimentón rojo o verde", claves:["pimenton","pimentón","pimiento"]},
  "espinaca":       {n:"Espinaca", cat:"verdura", u:"g", c:100, g:1, kcal:23, prot:2.9,
                     prod:"Espinaca fresca o congelada", claves:["espinaca","acelga"]},
  "brocoli":        {n:"Brócoli", cat:"verdura", u:"g", c:150, g:1, kcal:34, prot:2.8,
                     prod:"Brócoli fresco o congelado", claves:["brocoli","brócoli","coliflor"]},
  "pepino":         {n:"Pepino ensalada", cat:"verdura", u:"unidad", c:0.5, g:150, kcal:15, prot:0.7,
                     prod:"Pepino ensalada de la feria", claves:["pepino"]},

  // ---------- frutas ----------
  "platano":        {n:"Plátano", cat:"fruta", u:"unidad", c:1, g:120, kcal:89, prot:1.1,
                     prod:"Plátano de Ecuador, maduro", claves:["platano","plátano","banana"]},
  "manzana":        {n:"Manzana", cat:"fruta", u:"unidad", c:1, g:180, kcal:52, prot:0.3,
                     prod:"Manzana fuji o granny", claves:["manzana"]},
  "frutilla":       {n:"Frutillas", cat:"fruta", u:"g", c:120, g:1, kcal:32, prot:0.7,
                     prod:"Frutillas frescas o congeladas", claves:["frutilla","frutillas","fresa"]},
  "arandano":       {n:"Arándanos", cat:"fruta", u:"g", c:80, g:1, kcal:57, prot:0.7,
                     prod:"Arándanos frescos o congelados", claves:["arandano","arándano","berries"]},
  "naranja":        {n:"Naranja", cat:"fruta", u:"unidad", c:1, g:180, kcal:47, prot:0.9,
                     prod:"Naranja de jugo", claves:["naranja"]},
  "kiwi":           {n:"Kiwi", cat:"fruta", u:"unidad", c:1, g:75, kcal:61, prot:1.1,
                     prod:"Kiwi chileno", claves:["kiwi"]},
  "durazno":        {n:"Durazno", cat:"fruta", u:"unidad", c:1, g:150, kcal:39, prot:0.9,
                     prod:"Durazno de la temporada", claves:["durazno","damasco","melocoton"]},

  // ---------- frutos secos y semillas ----------
  "nueces":         {n:"Nueces", cat:"crocante", u:"g", c:20, g:1, kcal:654, prot:15,
                     prod:"Nueces chilenas peladas", claves:["nuez","nueces","frutos secos"]},
  "almendras":      {n:"Almendras", cat:"crocante", u:"g", c:20, g:1, kcal:575, prot:21,
                     prod:"Almendras chilenas", claves:["almendra","almendras","frutos secos"]},
  "mani":           {n:"Maní sin sal", cat:"crocante", u:"g", c:20, g:1, kcal:567, prot:26,
                     prod:"Maní natural sin sal", claves:["mani","maní","frutos secos"]},
  "pasas":          {n:"Pasas", cat:"crocante", u:"g", c:20, g:1, kcal:299, prot:3,
                     prod:"Pasas rubias", claves:["pasa","pasas"]},
  "chia":           {n:"Semillas de chía", cat:"crocante", u:"cda", c:1, g:12, kcal:486, prot:17,
                     prod:"Chía a granel o Vivo", claves:["chia","chía","semilla"]},
  "maravilla":      {n:"Semillas de maravilla", cat:"crocante", u:"cda", c:1, g:10, kcal:584, prot:21,
                     prod:"Pepas de maravilla peladas", claves:["maravilla","girasol","pepas","semilla"]},
  "granola":        {n:"Granola", cat:"crocante", u:"g", c:40, g:1, kcal:450, prot:9,
                     prod:"Granola Quaker o Vivo, baja en azúcar", claves:["granola","cereal"]},
  "mantequilla-mani":{n:"Mantequilla de maní", cat:"grasa", u:"cda", c:1, g:16, kcal:588, prot:25,
                     prod:"Mantequilla de maní natural (Vivo, Manare)", corto:"mantequilla de maní", claves:["mantequilla de mani","crema de mani","mani"]},

  // ---------- aliños y otros ----------
  "aceite-oliva":   {n:"Aceite de oliva", cat:"grasa", u:"cda", c:1, g:14, kcal:884, prot:0,
                     prod:"Aceite de oliva chileno (Olave, Terramater)", corto:"aceite de oliva", claves:["aceite","oliva"]},
  "limon":          {n:"Limón", cat:"alino", u:"unidad", c:0.5, g:60, kcal:29, prot:1.1,
                     prod:"Limón de Pica o común", claves:["limon","limón","jugo"]},
  "miel":           {n:"Miel", cat:"alino", u:"cdta", c:1, g:7, kcal:304, prot:0.3,
                     prod:"Miel de abeja chilena", claves:["miel","dulce","endulzar"]},
  "cilantro":       {n:"Cilantro", cat:"alino", u:"cda", c:1, g:4, kcal:23, prot:2.1,
                     prod:"Cilantro fresco de la feria", claves:["cilantro"]},
  "perejil":        {n:"Perejil", cat:"alino", u:"cda", c:1, g:4, kcal:36, prot:3,
                     prod:"Perejil fresco", claves:["perejil"]},
  "merken":         {n:"Merkén", cat:"alino", u:"cdta", c:0.5, g:2, kcal:280, prot:12,
                     prod:"Merkén de Temuco", claves:["merken","merkén","aji","picante"]},
  "oregano":        {n:"Orégano", cat:"alino", u:"cdta", c:0.5, g:1, kcal:265, prot:9,
                     prod:"Orégano seco", claves:["oregano","orégano"]},
  "comino":         {n:"Comino", cat:"alino", u:"cdta", c:0.5, g:2, kcal:375, prot:18,
                     prod:"Comino molido Gourmet", claves:["comino"]},
  "ajo":            {n:"Ajo", cat:"alino", u:"unidad", c:1, g:5, kcal:149, prot:6.4,
                     prod:"Ajo chilote", claves:["ajo"]},
  "aji-color":      {n:"Ají de color", cat:"alino", u:"cdta", c:0.5, g:2, kcal:282, prot:12,
                     prod:"Ají de color Gourmet", corto:"ají de color", claves:["aji de color","paprika","color"]},
  "sal":            {n:"Sal", cat:"alino", u:"pizca", c:1, g:1, kcal:0, prot:0,
                     prod:"Sal de mar Lobos", claves:["sal"]},
  "pimienta":       {n:"Pimienta", cat:"alino", u:"pizca", c:1, g:0.5, kcal:250, prot:10,
                     prod:"Pimienta negra molida", claves:["pimienta"]},
  "caldo":          {n:"Caldo de verduras", cat:"alino", u:"ml", c:400, g:1, kcal:4, prot:0.2,
                     prod:"Caldo casero o cubito Maggi bajo en sodio", claves:["caldo","sopa","cazuela"]},
  "mayo-light":     {n:"Mayonesa light", cat:"grasa", u:"cda", c:1, g:15, kcal:300, prot:0.5,
                     prod:"Hellmann's o Kraft light", claves:["mayonesa","mayo"]}
};
