/* Alimentos habituales con su composición POR 100 g (o por 100 ml en bebidas).
   Valores medios de tablas de composición: sirven para llevar la cuenta del día,
   no son análisis de laboratorio del producto exacto.

   kcal · prot/carb/gras/fib en gramos · na (sodio), ca (calcio), fe (hierro),
   k (potasio) y vc (vitamina C) en miligramos.
   u  = unidades de medida que se pueden elegir
   gr = cuánto pesa cada una de esas medidas, en gramos
   def= la medida y cantidad que sale por defecto
   com= en qué comidas aparece primero */

const MICROS = [
  {id:"fib", n:"Fibra",      u:"g",  rda:25,   tipo:"bueno"},
  {id:"na",  n:"Sodio",      u:"mg", rda:2000, tipo:"limite"},
  {id:"ca",  n:"Calcio",     u:"mg", rda:1200, tipo:"bueno"},
  {id:"fe",  n:"Hierro",     u:"mg", rda:8,    tipo:"bueno"},
  {id:"k",   n:"Potasio",    u:"mg", rda:3500, tipo:"bueno"},
  {id:"vc",  n:"Vitamina C", u:"mg", rda:75,   tipo:"bueno"}
];

const CATEGORIAS_HAB = [
  ["fruta",     "Frutas",      "🍎"],
  ["verdura",   "Verduras",    "🥦"],
  ["proteina",  "Proteínas",   "🍗"],
  ["lacteo",    "Lácteos y huevo", "🥛"],
  ["legumbre",  "Legumbres",   "🫘"],
  ["cereal",    "Cereales y pan", "🍞"],
  ["grasa",     "Grasas",      "🥑"],
  ["condimento","Condimentos", "🧂"],
  ["bebida",    "Bebidas",     "☕"],
  ["dulce",     "Dulces",      "🍫"]
];

const HABITUALES = {
  // ---------------- frutas ----------------
  "manzana":   {n:"Manzana", cat:"fruta", u:["unidad","g"], gr:{unidad:180}, def:{u:"unidad",c:1}, com:["desayuno","merienda"],
                kcal:52, prot:0.3, carb:14, gras:0.2, fib:2.4, na:1, ca:6, fe:0.1, k:107, vc:4.6},
  "platano":   {n:"Plátano", cat:"fruta", u:["unidad","g"], gr:{unidad:120}, def:{u:"unidad",c:1}, com:["desayuno","merienda"],
                kcal:89, prot:1.1, carb:23, gras:0.3, fib:2.6, na:1, ca:5, fe:0.3, k:358, vc:8.7},
  "naranja":   {n:"Naranja", cat:"fruta", u:["unidad","g"], gr:{unidad:180}, def:{u:"unidad",c:1}, com:["desayuno","merienda"],
                kcal:47, prot:0.9, carb:12, gras:0.1, fib:2.4, na:0, ca:40, fe:0.1, k:181, vc:53},
  "mandarina": {n:"Mandarina", cat:"fruta", u:["unidad","g"], gr:{unidad:80}, def:{u:"unidad",c:2}, com:["merienda"],
                kcal:53, prot:0.8, carb:13, gras:0.3, fib:1.8, na:2, ca:37, fe:0.2, k:166, vc:27},
  "pera":      {n:"Pera", cat:"fruta", u:["unidad","g"], gr:{unidad:170}, def:{u:"unidad",c:1}, com:["merienda"],
                kcal:57, prot:0.4, carb:15, gras:0.1, fib:3.1, na:1, ca:9, fe:0.2, k:116, vc:4.3},
  "uva":       {n:"Uvas", cat:"fruta", u:["g","unidad"], gr:{unidad:5}, def:{u:"g",c:100}, com:["merienda"],
                kcal:69, prot:0.7, carb:18, gras:0.2, fib:0.9, na:2, ca:10, fe:0.4, k:191, vc:3.2},
  "frutilla":  {n:"Frutillas", cat:"fruta", u:["g","unidad"], gr:{unidad:12}, def:{u:"g",c:120}, com:["desayuno","merienda"],
                kcal:32, prot:0.7, carb:7.7, gras:0.3, fib:2, na:1, ca:16, fe:0.4, k:153, vc:59},
  "arandano":  {n:"Arándanos", cat:"fruta", u:["g","cda"], gr:{cda:12}, def:{u:"g",c:80}, com:["desayuno"],
                kcal:57, prot:0.7, carb:14, gras:0.3, fib:2.4, na:1, ca:6, fe:0.3, k:77, vc:9.7},
  "kiwi":      {n:"Kiwi", cat:"fruta", u:["unidad","g"], gr:{unidad:75}, def:{u:"unidad",c:1}, com:["desayuno","merienda"],
                kcal:61, prot:1.1, carb:15, gras:0.5, fib:3, na:3, ca:34, fe:0.3, k:312, vc:93},
  "palta":     {n:"Palta", cat:"fruta", u:["unidad","g","cda"], gr:{unidad:200, cda:25}, def:{u:"unidad",c:0.5}, com:["desayuno","cena"],
                kcal:160, prot:2, carb:9, gras:15, fib:6.7, na:7, ca:12, fe:0.6, k:485, vc:10},
  "melon":     {n:"Melón", cat:"fruta", u:["g","unidad"], gr:{unidad:200}, def:{u:"g",c:200}, com:["merienda"],
                kcal:34, prot:0.8, carb:8, gras:0.2, fib:0.9, na:16, ca:9, fe:0.2, k:267, vc:37},
  "sandia":    {n:"Sandía", cat:"fruta", u:["g"], gr:{}, def:{u:"g",c:200}, com:["merienda"],
                kcal:30, prot:0.6, carb:7.6, gras:0.2, fib:0.4, na:1, ca:7, fe:0.2, k:112, vc:8},
  "pina":      {n:"Piña", cat:"fruta", u:["g"], gr:{}, def:{u:"g",c:150}, com:["merienda"],
                kcal:50, prot:0.5, carb:13, gras:0.1, fib:1.4, na:1, ca:13, fe:0.3, k:109, vc:48},
  "durazno":   {n:"Durazno", cat:"fruta", u:["unidad","g"], gr:{unidad:150}, def:{u:"unidad",c:1}, com:["merienda"],
                kcal:39, prot:0.9, carb:10, gras:0.3, fib:1.5, na:0, ca:6, fe:0.3, k:190, vc:6.6},
  "ciruela":   {n:"Ciruela", cat:"fruta", u:["unidad","g"], gr:{unidad:60}, def:{u:"unidad",c:2}, com:["merienda"],
                kcal:46, prot:0.7, carb:11, gras:0.3, fib:1.4, na:0, ca:6, fe:0.2, k:157, vc:9.5},
  "chirimoya": {n:"Chirimoya", cat:"fruta", u:["unidad","g"], gr:{unidad:200}, def:{u:"unidad",c:0.5}, com:["merienda"],
                kcal:75, prot:1.6, carb:18, gras:0.7, fib:3, na:7, ca:10, fe:0.3, k:287, vc:12},
  "papaya":    {n:"Papaya", cat:"fruta", u:["g"], gr:{}, def:{u:"g",c:150}, com:["desayuno"],
                kcal:43, prot:0.5, carb:11, gras:0.3, fib:1.7, na:8, ca:20, fe:0.3, k:182, vc:61},
  "pasas":     {n:"Pasas", cat:"fruta", u:["cda","g"], gr:{cda:10}, def:{u:"cda",c:1}, com:["desayuno"],
                kcal:299, prot:3.1, carb:79, gras:0.5, fib:3.7, na:11, ca:50, fe:1.9, k:749, vc:2.3},

  // ---------------- verduras ----------------
  "tomate":    {n:"Tomate", cat:"verdura", u:["unidad","g"], gr:{unidad:120}, def:{u:"unidad",c:1}, com:["comida","cena"],
                kcal:18, prot:0.9, carb:3.9, gras:0.2, fib:1.2, na:5, ca:10, fe:0.3, k:237, vc:14},
  "lechuga":   {n:"Lechuga", cat:"verdura", u:["g"], gr:{}, def:{u:"g",c:80}, com:["comida","cena"],
                kcal:15, prot:1.4, carb:2.9, gras:0.2, fib:1.3, na:28, ca:36, fe:0.9, k:194, vc:9},
  "zanahoria": {n:"Zanahoria", cat:"verdura", u:["unidad","g"], gr:{unidad:80}, def:{u:"unidad",c:1}, com:["comida","cena"],
                kcal:41, prot:0.9, carb:10, gras:0.2, fib:2.8, na:69, ca:33, fe:0.3, k:320, vc:5.9},
  "cebolla":   {n:"Cebolla", cat:"verdura", u:["unidad","g"], gr:{unidad:120}, def:{u:"unidad",c:0.5}, com:["comida","cena"],
                kcal:40, prot:1.1, carb:9.3, gras:0.1, fib:1.7, na:4, ca:23, fe:0.2, k:146, vc:7.4},
  "pepino":    {n:"Pepino", cat:"verdura", u:["unidad","g"], gr:{unidad:150}, def:{u:"unidad",c:0.5}, com:["comida","cena"],
                kcal:15, prot:0.7, carb:3.6, gras:0.1, fib:0.5, na:2, ca:16, fe:0.3, k:147, vc:2.8},
  "pimenton":  {n:"Pimentón", cat:"verdura", u:["unidad","g"], gr:{unidad:150}, def:{u:"unidad",c:0.5}, com:["comida","cena"],
                kcal:31, prot:1, carb:6, gras:0.3, fib:2.1, na:4, ca:7, fe:0.4, k:211, vc:128},
  "brocoli":   {n:"Brócoli", cat:"verdura", u:["g","taza"], gr:{taza:90}, def:{u:"g",c:150}, com:["comida","cena"],
                kcal:34, prot:2.8, carb:7, gras:0.4, fib:2.6, na:33, ca:47, fe:0.7, k:316, vc:89},
  "espinaca":  {n:"Espinaca", cat:"verdura", u:["g","taza"], gr:{taza:30}, def:{u:"g",c:100}, com:["comida","cena"],
                kcal:23, prot:2.9, carb:3.6, gras:0.4, fib:2.2, na:79, ca:99, fe:2.7, k:558, vc:28},
  "acelga":    {n:"Acelga", cat:"verdura", u:["g"], gr:{}, def:{u:"g",c:120}, com:["comida"],
                kcal:19, prot:1.8, carb:3.7, gras:0.2, fib:1.6, na:213, ca:51, fe:1.8, k:379, vc:30},
  "zapallo-italiano":{n:"Zapallo italiano", cat:"verdura", u:["unidad","g"], gr:{unidad:200}, def:{u:"unidad",c:1}, com:["comida","cena"],
                kcal:17, prot:1.2, carb:3.1, gras:0.3, fib:1, na:8, ca:16, fe:0.4, k:261, vc:18},
  "zapallo":   {n:"Zapallo camote", cat:"verdura", u:["g"], gr:{}, def:{u:"g",c:200}, com:["comida"],
                kcal:26, prot:1, carb:6.5, gras:0.1, fib:0.5, na:1, ca:21, fe:0.8, k:340, vc:9},
  "coliflor":  {n:"Coliflor", cat:"verdura", u:["g"], gr:{}, def:{u:"g",c:150}, com:["comida","cena"],
                kcal:25, prot:1.9, carb:5, gras:0.3, fib:2, na:30, ca:22, fe:0.4, k:299, vc:48},
  "poroto-verde":{n:"Porotos verdes", cat:"verdura", u:["g"], gr:{}, def:{u:"g",c:150}, com:["comida"],
                kcal:31, prot:1.8, carb:7, gras:0.2, fib:2.7, na:6, ca:37, fe:1, k:211, vc:12},
  "choclo":    {n:"Choclo", cat:"verdura", u:["g","unidad","cda"], gr:{unidad:150, cda:15}, def:{u:"g",c:100}, com:["comida"],
                kcal:96, prot:3.4, carb:21, gras:1.5, fib:2.7, na:15, ca:2, fe:0.5, k:270, vc:6.8},
  "betarraga": {n:"Betarraga", cat:"verdura", u:["g","unidad"], gr:{unidad:100}, def:{u:"g",c:100}, com:["comida"],
                kcal:43, prot:1.6, carb:10, gras:0.2, fib:2.8, na:78, ca:16, fe:0.8, k:325, vc:4.9},
  "apio":      {n:"Apio", cat:"verdura", u:["g"], gr:{}, def:{u:"g",c:60}, com:["comida"],
                kcal:16, prot:0.7, carb:3, gras:0.2, fib:1.6, na:80, ca:40, fe:0.2, k:260, vc:3.1},
  "champinon": {n:"Champiñones", cat:"verdura", u:["g"], gr:{}, def:{u:"g",c:100}, com:["comida","cena"],
                kcal:22, prot:3.1, carb:3.3, gras:0.3, fib:1, na:5, ca:3, fe:0.5, k:318, vc:2.1},
  "repollo":   {n:"Repollo", cat:"verdura", u:["g"], gr:{}, def:{u:"g",c:100}, com:["comida"],
                kcal:25, prot:1.3, carb:5.8, gras:0.1, fib:2.5, na:18, ca:40, fe:0.5, k:170, vc:37},
  "papa":      {n:"Papa cocida", cat:"verdura", u:["unidad","g"], gr:{unidad:150}, def:{u:"unidad",c:1}, com:["comida"],
                kcal:86, prot:1.9, carb:20, gras:0.1, fib:1.8, na:5, ca:8, fe:0.3, k:379, vc:13},
  "camote":    {n:"Camote", cat:"verdura", u:["g","unidad"], gr:{unidad:180}, def:{u:"g",c:150}, com:["comida"],
                kcal:86, prot:1.6, carb:20, gras:0.1, fib:3, na:55, ca:30, fe:0.6, k:337, vc:2.4},
  "alcachofa": {n:"Alcachofa", cat:"verdura", u:["unidad","g"], gr:{unidad:120}, def:{u:"unidad",c:1}, com:["comida"],
                kcal:47, prot:3.3, carb:11, gras:0.2, fib:5.4, na:94, ca:44, fe:1.3, k:370, vc:11},
  // ---------------- proteínas ----------------
  "pollo-pechuga":{n:"Pechuga de pollo", cat:"proteina", u:["g","unidad"], gr:{unidad:150}, def:{u:"g",c:150}, com:["comida","cena"],
                kcal:165, prot:31, carb:0, gras:3.6, fib:0, na:74, ca:15, fe:1, k:256, vc:0},
  "pollo-trutro":{n:"Trutro de pollo", cat:"proteina", u:["unidad","g"], gr:{unidad:150}, def:{u:"unidad",c:1}, com:["comida"],
                kcal:190, prot:26, carb:0, gras:9, fib:0, na:90, ca:12, fe:1, k:230, vc:0},
  "carne-molida":{n:"Carne molida", cat:"proteina", u:["g"], gr:{}, def:{u:"g",c:120}, com:["comida"],
                kcal:215, prot:26, carb:0, gras:12, fib:0, na:70, ca:18, fe:2.6, k:330, vc:0},
  "lomo-cerdo":{n:"Lomo de cerdo", cat:"proteina", u:["g"], gr:{}, def:{u:"g",c:150}, com:["comida"],
                kcal:195, prot:27, carb:0, gras:9, fib:0, na:60, ca:10, fe:0.9, k:370, vc:0},
  "salmon":    {n:"Salmón", cat:"proteina", u:["g"], gr:{}, def:{u:"g",c:150}, com:["comida","cena"],
                kcal:208, prot:22, carb:0, gras:13, fib:0, na:59, ca:12, fe:0.3, k:363, vc:0},
  "merluza":   {n:"Merluza", cat:"proteina", u:["g"], gr:{}, def:{u:"g",c:180}, com:["cena"],
                kcal:90, prot:18, carb:0, gras:1.3, fib:0, na:89, ca:20, fe:0.4, k:400, vc:0},
  "reineta":   {n:"Reineta", cat:"proteina", u:["g"], gr:{}, def:{u:"g",c:180}, com:["cena"],
                kcal:95, prot:19, carb:0, gras:2, fib:0, na:85, ca:20, fe:0.5, k:390, vc:0},
  "atun-agua": {n:"Atún al agua", cat:"proteina", u:["g","unidad"], gr:{unidad:120}, def:{u:"g",c:120}, com:["comida","cena"],
                kcal:110, prot:24, carb:0, gras:1, fib:0, na:350, ca:10, fe:1, k:240, vc:0},
  "jamon-pavo":{n:"Jamón de pavo", cat:"proteina", u:["g","unidad"], gr:{unidad:20}, def:{u:"unidad",c:2}, com:["desayuno","merienda"],
                kcal:110, prot:17, carb:2, gras:3.5, fib:0, na:1000, ca:10, fe:0.7, k:300, vc:0},
  "longaniza": {n:"Longaniza", cat:"proteina", u:["unidad","g"], gr:{unidad:80}, def:{u:"unidad",c:1}, com:["comida"],
                kcal:380, prot:15, carb:2, gras:34, fib:0, na:1200, ca:15, fe:1.5, k:250, vc:0},
  "tofu":      {n:"Tofu", cat:"proteina", u:["g"], gr:{}, def:{u:"g",c:100}, com:["comida","cena"],
                kcal:145, prot:16, carb:3, gras:9, fib:1, na:12, ca:350, fe:2.7, k:120, vc:0},

  // ---------------- lácteos y huevo ----------------
  "huevo":     {n:"Huevo", cat:"lacteo", u:["unidad","g"], gr:{unidad:55}, def:{u:"unidad",c:2}, com:["desayuno","cena"],
                kcal:143, prot:12.6, carb:0.7, gras:9.5, fib:0, na:142, ca:56, fe:1.8, k:138, vc:0},
  "leche-desc":{n:"Leche descremada", cat:"lacteo", u:["ml","taza"], gr:{taza:200}, def:{u:"taza",c:1}, com:["desayuno","merienda"],
                kcal:35, prot:3.4, carb:5, gras:0.2, fib:0, na:44, ca:123, fe:0, k:150, vc:0},
  "leche-entera":{n:"Leche entera", cat:"lacteo", u:["ml","taza"], gr:{taza:200}, def:{u:"taza",c:1}, com:["desayuno"],
                kcal:61, prot:3.2, carb:4.8, gras:3.3, fib:0, na:43, ca:113, fe:0, k:143, vc:0},
  "yogur-natural":{n:"Yogur natural", cat:"lacteo", u:["unidad","g"], gr:{unidad:125}, def:{u:"unidad",c:1}, com:["desayuno","merienda"],
                kcal:61, prot:3.5, carb:4.7, gras:3.3, fib:0, na:46, ca:121, fe:0.1, k:155, vc:0.5},
  "yogur-proteina":{n:"Yogur con proteína", cat:"lacteo", u:["unidad","g"], gr:{unidad:170}, def:{u:"unidad",c:1}, com:["desayuno","merienda"],
                kcal:97, prot:9, carb:4, gras:3.5, fib:0, na:36, ca:110, fe:0.1, k:141, vc:0},
  "quesillo":  {n:"Quesillo", cat:"lacteo", u:["g","unidad"], gr:{unidad:80}, def:{u:"g",c:60}, com:["desayuno","merienda"],
                kcal:98, prot:12, carb:3.4, gras:4.3, fib:0, na:330, ca:90, fe:0.1, k:104, vc:0},
  "queso":     {n:"Queso mantecoso", cat:"lacteo", u:["g","unidad"], gr:{unidad:25}, def:{u:"unidad",c:1}, com:["desayuno","merienda"],
                kcal:350, prot:24, carb:2, gras:28, fib:0, na:700, ca:700, fe:0.2, k:100, vc:0},
  "queso-crema":{n:"Queso crema", cat:"lacteo", u:["cda","g"], gr:{cda:15}, def:{u:"cda",c:1}, com:["desayuno"],
                kcal:250, prot:6, carb:4, gras:24, fib:0, na:300, ca:90, fe:0.1, k:130, vc:0},
  "mantequilla":{n:"Mantequilla", cat:"lacteo", u:["cdta","cda","g"], gr:{cdta:5, cda:14}, def:{u:"cdta",c:1}, com:["desayuno"],
                kcal:717, prot:0.9, carb:0.1, gras:81, fib:0, na:11, ca:24, fe:0, k:24, vc:0},

  // ---------------- legumbres ----------------
  "lentejas":  {n:"Lentejas cocidas", cat:"legumbre", u:["g","taza"], gr:{taza:200}, def:{u:"g",c:200}, com:["comida"],
                kcal:116, prot:9, carb:20, gras:0.4, fib:7.9, na:2, ca:19, fe:3.3, k:369, vc:1.5},
  "garbanzos": {n:"Garbanzos cocidos", cat:"legumbre", u:["g","taza"], gr:{taza:200}, def:{u:"g",c:180}, com:["comida"],
                kcal:164, prot:8.9, carb:27, gras:2.6, fib:7.6, na:7, ca:49, fe:2.9, k:291, vc:1.3},
  "porotos":   {n:"Porotos cocidos", cat:"legumbre", u:["g","taza"], gr:{taza:200}, def:{u:"g",c:180}, com:["comida"],
                kcal:127, prot:8.7, carb:23, gras:0.5, fib:6.4, na:2, ca:35, fe:2.1, k:405, vc:0},
  "arvejas":   {n:"Arvejas", cat:"legumbre", u:["g","cda"], gr:{cda:15}, def:{u:"g",c:100}, com:["comida"],
                kcal:81, prot:5.4, carb:14, gras:0.4, fib:5.1, na:5, ca:25, fe:1.5, k:244, vc:40},
  "quinoa":    {n:"Quinoa cocida", cat:"legumbre", u:["g","taza"], gr:{taza:180}, def:{u:"g",c:150}, com:["comida","cena"],
                kcal:120, prot:4.4, carb:21, gras:1.9, fib:2.8, na:7, ca:17, fe:1.5, k:172, vc:0},

  // ---------------- cereales y pan ----------------
  "arroz":     {n:"Arroz cocido", cat:"cereal", u:["g","taza","cda"], gr:{taza:180, cda:20}, def:{u:"g",c:150}, com:["comida"],
                kcal:130, prot:2.7, carb:28, gras:0.3, fib:0.4, na:1, ca:10, fe:0.2, k:35, vc:0},
  "fideos":    {n:"Fideos cocidos", cat:"cereal", u:["g","taza"], gr:{taza:180}, def:{u:"g",c:180}, com:["comida"],
                kcal:158, prot:5.8, carb:31, gras:0.9, fib:1.8, na:1, ca:7, fe:0.5, k:44, vc:0},
  "avena":     {n:"Avena", cat:"cereal", u:["cda","g","taza"], gr:{cda:10, taza:80}, def:{u:"cda",c:4}, com:["desayuno"],
                kcal:389, prot:13, carb:66, gras:7, fib:10, na:2, ca:54, fe:4.7, k:429, vc:0},
  "marraqueta":{n:"Marraqueta", cat:"cereal", u:["unidad","g"], gr:{unidad:100}, def:{u:"unidad",c:0.5}, com:["desayuno","merienda"],
                kcal:265, prot:8, carb:52, gras:1, fib:2.5, na:560, ca:30, fe:1.5, k:120, vc:0},
  "pan-integral":{n:"Pan integral", cat:"cereal", u:["unidad","g"], gr:{unidad:30}, def:{u:"unidad",c:2}, com:["desayuno","merienda"],
                kcal:247, prot:10, carb:41, gras:3.5, fib:6, na:450, ca:70, fe:2.5, k:230, vc:0},
  "galleta-arroz":{n:"Galletas de arroz", cat:"cereal", u:["unidad","g"], gr:{unidad:8}, def:{u:"unidad",c:3}, com:["merienda"],
                kcal:375, prot:7.5, carb:81, gras:3, fib:3, na:10, ca:10, fe:0.6, k:120, vc:0},
  "granola":   {n:"Granola", cat:"cereal", u:["cda","g"], gr:{cda:12}, def:{u:"cda",c:3}, com:["desayuno"],
                kcal:450, prot:9, carb:64, gras:17, fib:7, na:30, ca:60, fe:2.5, k:330, vc:0},
  "mote":      {n:"Mote cocido", cat:"cereal", u:["g","taza"], gr:{taza:180}, def:{u:"g",c:150}, com:["comida"],
                kcal:120, prot:3.5, carb:26, gras:0.5, fib:2, na:3, ca:15, fe:1, k:90, vc:0},
  "tortilla":  {n:"Tortilla de trigo", cat:"cereal", u:["unidad","g"], gr:{unidad:45}, def:{u:"unidad",c:1}, com:["cena"],
                kcal:300, prot:8, carb:50, gras:7, fib:3, na:500, ca:100, fe:2.5, k:130, vc:0},

  // ---------------- grasas ----------------
  "aceite-oliva":{n:"Aceite de oliva", cat:"grasa", u:["cdta","cda","ml"], gr:{cdta:5, cda:14}, def:{u:"cda",c:1}, com:["comida","cena"],
                kcal:884, prot:0, carb:0, gras:100, fib:0, na:2, ca:1, fe:0.6, k:1, vc:0},
  "aceite-maravilla":{n:"Aceite de maravilla", cat:"grasa", u:["cdta","cda","ml"], gr:{cdta:5, cda:14}, def:{u:"cda",c:1}, com:["comida"],
                kcal:884, prot:0, carb:0, gras:100, fib:0, na:0, ca:0, fe:0, k:0, vc:0},
  "nueces":    {n:"Nueces", cat:"grasa", u:["unidad","g","cda"], gr:{unidad:5, cda:15}, def:{u:"unidad",c:4}, com:["desayuno","merienda"],
                kcal:654, prot:15, carb:14, gras:65, fib:6.7, na:2, ca:98, fe:2.9, k:441, vc:1.3},
  "almendras": {n:"Almendras", cat:"grasa", u:["unidad","g","cda"], gr:{unidad:1.2, cda:15}, def:{u:"g",c:20}, com:["desayuno","merienda"],
                kcal:575, prot:21, carb:22, gras:49, fib:12, na:1, ca:269, fe:3.7, k:733, vc:0},
  "mani":      {n:"Maní", cat:"grasa", u:["g","cda"], gr:{cda:15}, def:{u:"g",c:20}, com:["merienda"],
                kcal:567, prot:26, carb:16, gras:49, fib:8.5, na:18, ca:92, fe:4.6, k:705, vc:0},
  "mantequilla-mani":{n:"Mantequilla de maní", cat:"grasa", u:["cda","cdta","g"], gr:{cda:16, cdta:6}, def:{u:"cda",c:1}, com:["desayuno","merienda"],
                kcal:588, prot:25, carb:20, gras:50, fib:6, na:350, ca:43, fe:1.9, k:649, vc:0},
  "chia":      {n:"Semillas de chía", cat:"grasa", u:["cda","cdta","g"], gr:{cda:12, cdta:4}, def:{u:"cda",c:1}, com:["desayuno"],
                kcal:486, prot:17, carb:42, gras:31, fib:34, na:16, ca:631, fe:7.7, k:407, vc:1.6},
  "maravilla": {n:"Pepas de maravilla", cat:"grasa", u:["cda","g"], gr:{cda:10}, def:{u:"cda",c:1}, com:["merienda"],
                kcal:584, prot:21, carb:20, gras:51, fib:8.6, na:9, ca:78, fe:5.2, k:645, vc:1.4},
  "aceituna":  {n:"Aceitunas", cat:"grasa", u:["unidad","g"], gr:{unidad:5}, def:{u:"unidad",c:6}, com:["comida"],
                kcal:145, prot:1, carb:6, gras:15, fib:3.2, na:1500, ca:88, fe:3.3, k:8, vc:0},
  "mayonesa":  {n:"Mayonesa", cat:"grasa", u:["cda","cdta"], gr:{cda:15, cdta:5}, def:{u:"cda",c:1}, com:["comida"],
                kcal:680, prot:1, carb:1, gras:75, fib:0, na:600, ca:8, fe:0.2, k:20, vc:0},

  // ---------------- condimentos ----------------
  "sal":       {n:"Sal", cat:"condimento", u:["pizca","cdta","g"], gr:{pizca:0.5, cdta:5}, def:{u:"pizca",c:1}, com:["comida","cena"],
                kcal:0, prot:0, carb:0, gras:0, fib:0, na:38700, ca:24, fe:0.3, k:8, vc:0},
  "limon-jugo":{n:"Jugo de limón", cat:"condimento", u:["cda","cdta","unidad"], gr:{cda:15, cdta:5, unidad:30}, def:{u:"cda",c:1}, com:["comida","cena"],
                kcal:22, prot:0.4, carb:6.9, gras:0.2, fib:0.3, na:1, ca:6, fe:0.1, k:103, vc:39},
  "ajo":       {n:"Ajo", cat:"condimento", u:["unidad","cdta"], gr:{unidad:5, cdta:3}, def:{u:"unidad",c:1}, com:["comida","cena"],
                kcal:149, prot:6.4, carb:33, gras:0.5, fib:2.1, na:17, ca:181, fe:1.7, k:401, vc:31},
  "merken":    {n:"Merkén", cat:"condimento", u:["cdta","pizca"], gr:{cdta:2, pizca:0.5}, def:{u:"cdta",c:0.5}, com:["comida","cena"],
                kcal:280, prot:12, carb:50, gras:13, fib:28, na:50, ca:150, fe:8, k:1200, vc:5},
  "oregano":   {n:"Orégano", cat:"condimento", u:["cdta","pizca"], gr:{cdta:1, pizca:0.3}, def:{u:"cdta",c:0.5}, com:["comida","cena"],
                kcal:265, prot:9, carb:69, gras:4.3, fib:42, na:25, ca:1597, fe:36, k:1260, vc:2.3},
  "comino":    {n:"Comino", cat:"condimento", u:["cdta","pizca"], gr:{cdta:2, pizca:0.5}, def:{u:"cdta",c:0.5}, com:["comida"],
                kcal:375, prot:18, carb:44, gras:22, fib:11, na:168, ca:931, fe:66, k:1788, vc:7.7},
  "pimienta":  {n:"Pimienta", cat:"condimento", u:["pizca","cdta"], gr:{pizca:0.3, cdta:2}, def:{u:"pizca",c:1}, com:["comida","cena"],
                kcal:251, prot:10, carb:64, gras:3.3, fib:25, na:20, ca:443, fe:9.7, k:1329, vc:0},
  "cilantro":  {n:"Cilantro", cat:"condimento", u:["cda","g"], gr:{cda:4}, def:{u:"cda",c:1}, com:["comida","cena"],
                kcal:23, prot:2.1, carb:3.7, gras:0.5, fib:2.8, na:46, ca:67, fe:1.8, k:521, vc:27},
  "perejil":   {n:"Perejil", cat:"condimento", u:["cda","g"], gr:{cda:4}, def:{u:"cda",c:1}, com:["comida","cena"],
                kcal:36, prot:3, carb:6.3, gras:0.8, fib:3.3, na:56, ca:138, fe:6.2, k:554, vc:133},
  "vinagre":   {n:"Vinagre", cat:"condimento", u:["cda","cdta"], gr:{cda:15, cdta:5}, def:{u:"cda",c:1}, com:["comida"],
                kcal:20, prot:0, carb:0.9, gras:0, fib:0, na:5, ca:6, fe:0.2, k:73, vc:0},
  "soya":      {n:"Salsa de soya", cat:"condimento", u:["cda","cdta"], gr:{cda:15, cdta:5}, def:{u:"cda",c:1}, com:["comida","cena"],
                kcal:60, prot:8, carb:6, gras:0.1, fib:0.8, na:5500, ca:20, fe:1.4, k:180, vc:0},
  "mostaza":   {n:"Mostaza", cat:"condimento", u:["cdta","cda"], gr:{cdta:5, cda:15}, def:{u:"cdta",c:1}, com:["comida"],
                kcal:66, prot:4, carb:5, gras:3.3, fib:3.3, na:1100, ca:58, fe:1.5, k:150, vc:1.5},
  "ketchup":   {n:"Kétchup", cat:"condimento", u:["cda","cdta"], gr:{cda:15, cdta:5}, def:{u:"cda",c:1}, com:["comida"],
                kcal:110, prot:1.2, carb:26, gras:0.1, fib:0.3, na:900, ca:15, fe:0.4, k:280, vc:4},
  "azucar":    {n:"Azúcar", cat:"condimento", u:["cdta","cda","g"], gr:{cdta:5, cda:12}, def:{u:"cdta",c:1}, com:["desayuno","merienda"],
                kcal:400, prot:0, carb:100, gras:0, fib:0, na:1, ca:1, fe:0, k:2, vc:0},
  "miel":      {n:"Miel", cat:"condimento", u:["cdta","cda"], gr:{cdta:7, cda:21}, def:{u:"cdta",c:1}, com:["desayuno"],
                kcal:304, prot:0.3, carb:82, gras:0, fib:0.2, na:4, ca:6, fe:0.4, k:52, vc:0.5},
  "endulzante":{n:"Endulzante", cat:"condimento", u:["cdta","unidad"], gr:{cdta:1, unidad:0.5}, def:{u:"cdta",c:1}, com:["desayuno","merienda"],
                kcal:0, prot:0, carb:0, gras:0, fib:0, na:0, ca:0, fe:0, k:0, vc:0},

  // ---------------- bebidas ----------------
  "agua":      {n:"Agua", cat:"bebida", u:["ml","taza"], gr:{taza:250}, def:{u:"taza",c:1}, com:["desayuno","comida","merienda","cena"],
                kcal:0, prot:0, carb:0, gras:0, fib:0, na:2, ca:5, fe:0, k:1, vc:0},
  "cafe":      {n:"Café solo", cat:"bebida", u:["taza","ml"], gr:{taza:100}, def:{u:"taza",c:1}, com:["desayuno","merienda"],
                kcal:2, prot:0.1, carb:0, gras:0, fib:0, na:2, ca:2, fe:0, k:49, vc:0},
  "te":        {n:"Té", cat:"bebida", u:["taza","ml"], gr:{taza:250}, def:{u:"taza",c:1}, com:["desayuno","merienda"],
                kcal:1, prot:0, carb:0.3, gras:0, fib:0, na:3, ca:0, fe:0, k:37, vc:0},
  "te-leche":  {n:"Té con leche", cat:"bebida", u:["taza","ml"], gr:{taza:250}, def:{u:"taza",c:1}, com:["desayuno","merienda"],
                kcal:45, prot:2, carb:4, gras:2, fib:0, na:30, ca:80, fe:0, k:100, vc:0},
  "jugo-naranja":{n:"Jugo de naranja natural", cat:"bebida", u:["ml","taza"], gr:{taza:200}, def:{u:"taza",c:1}, com:["desayuno"],
                kcal:45, prot:0.7, carb:10, gras:0.2, fib:0.2, na:1, ca:11, fe:0.2, k:200, vc:50},
  "bebida-cola":{n:"Bebida de fantasía", cat:"bebida", u:["ml","unidad"], gr:{unidad:350}, def:{u:"unidad",c:1}, com:["comida"],
                kcal:42, prot:0, carb:10.6, gras:0, fib:0, na:4, ca:2, fe:0.1, k:2, vc:0},
  "bebida-zero":{n:"Bebida zero", cat:"bebida", u:["ml","unidad"], gr:{unidad:350}, def:{u:"unidad",c:1}, com:["comida"],
                kcal:0, prot:0, carb:0, gras:0, fib:0, na:12, ca:2, fe:0, k:2, vc:0},
  "leche-almendra":{n:"Bebida de almendras", cat:"bebida", u:["ml","taza"], gr:{taza:200}, def:{u:"taza",c:1}, com:["desayuno"],
                kcal:22, prot:0.6, carb:1, gras:1.5, fib:0.3, na:60, ca:180, fe:0.3, k:60, vc:0},

  // ---------------- dulces ----------------
  "chocolate-amargo":{n:"Chocolate amargo 70%", cat:"dulce", u:["unidad","g"], gr:{unidad:10}, def:{u:"unidad",c:2}, com:["merienda"],
                kcal:550, prot:8, carb:46, gras:40, fib:11, na:20, ca:70, fe:11, k:715, vc:0},
  "manjar":    {n:"Manjar", cat:"dulce", u:["cda","cdta"], gr:{cda:20, cdta:7}, def:{u:"cda",c:1}, com:["merienda"],
                kcal:315, prot:6, carb:55, gras:8, fib:0, na:130, ca:200, fe:0.2, k:280, vc:0},
  "helado":    {n:"Helado", cat:"dulce", u:["g","unidad"], gr:{unidad:60}, def:{u:"unidad",c:1}, com:["merienda"],
                kcal:200, prot:3.5, carb:24, gras:11, fib:0.7, na:80, ca:128, fe:0.1, k:199, vc:0.6},
  "alfajor":   {n:"Alfajor", cat:"dulce", u:["unidad","g"], gr:{unidad:40}, def:{u:"unidad",c:1}, com:["merienda"],
                kcal:420, prot:5, carb:60, gras:18, fib:1.5, na:200, ca:80, fe:1.2, k:180, vc:0}
};
