/* Los productos que compra Gema, transcritos de las etiquetas del catálogo que mandó.
   Los valores son POR 100 g (o por 100 ml), calculados desde la etiqueta cuando esta
   solo traía la columna de la porción. Lo que la etiqueta no dice queda en null: la app
   lo cuenta como dato que falta en vez de inventárselo.

   medida = la porción tal como viene en el envase · sat = grasa saturada · azu = azúcares */

const PRODUCTOS = {
  "p-yogur-batido-natural-1": {n:"Yogur batido natural En Simple", marca:"Soprole", cat:"lacteo", prod:true,
      medida:"1 unidad (120 g)", u:["porcion","g"], gr:{porcion:120}, def:{u:"porcion",c:1},
      com:["desayuno", "merienda"],
      kcal:73, prot:3.4, carb:4.8, gras:4.5, fib:null, na:33, ca:92, fe:null, k:null, vc:null, sat:3.2, azu:4.8},
  "p-leche-natural-descremada-2": {n:"Leche natural descremada", marca:"Soprole", cat:"lacteo", prod:true,
      medida:"1 vaso (200 ml)", u:["porcion","g"], gr:{porcion:200}, def:{u:"porcion",c:1},
      com:["desayuno", "merienda"],
      kcal:32, prot:3.3, carb:4.6, gras:0.12, fib:null, na:38, ca:101, fe:null, k:null, vc:null, sat:0.08, azu:4.6},
  "p-queso-chacra-3": {n:"Queso Chacra", marca:"Quillayes", cat:"lacteo", prod:true,
      medida:"1 rebanada (30 g)", u:["porcion","g"], gr:{porcion:30}, def:{u:"porcion",c:1},
      com:["desayuno", "merienda", "cena"],
      kcal:187, prot:12.7, carb:2.4, gras:14.1, fib:null, na:300, ca:362, fe:null, k:null, vc:null, sat:9.94, azu:1.2},
  "p-mozzarella-fior-di-4": {n:"Mozzarella Fior di Latte", marca:"Granarolo", cat:"lacteo", prod:true,
      medida:"1 trozo (30 g)", u:["porcion","g"], gr:{porcion:30}, def:{u:"porcion",c:1},
      com:["comida", "cena"],
      kcal:211, prot:18.5, carb:1, gras:20, fib:null, na:300, ca:null, fe:null, k:null, vc:null, sat:11.8, azu:1},
  "p-queso-mozzarella-en-5": {n:"Queso mozzarella en hebras", marca:"Soprole", cat:"lacteo", prod:true,
      medida:"1 cucharada (10 g)", u:["porcion","g"], gr:{porcion:10}, def:{u:"porcion",c:1},
      com:["comida", "cena"],
      kcal:342, prot:23.8, carb:2.9, gras:26.1, fib:null, na:524, ca:null, fe:null, k:null, vc:null, sat:17.5, azu:2.9},
  "p-queso-brie-la-6": {n:"Queso Brie La Tabla", marca:"Soprole", cat:"lacteo", prod:true,
      medida:"1 rebanada (30 g)", u:["porcion","g"], gr:{porcion:30}, def:{u:"porcion",c:1},
      com:["merienda", "cena"],
      kcal:291, prot:18.5, carb:0, gras:24, fib:null, na:600, ca:499, fe:null, k:null, vc:null, sat:15, azu:0},
  "p-kefir-natural-sin-7": {n:"Kéfir natural sin endulzar", marca:"Quillayes", cat:"lacteo", prod:true,
      medida:"1 unidad (80 ml)", u:["porcion","g"], gr:{porcion:80}, def:{u:"porcion",c:1},
      com:["desayuno", "merienda"],
      kcal:49, prot:3.5, carb:4.9, gras:1.7, fib:null, na:44, ca:123, fe:null, k:null, vc:null, sat:1.1, azu:4.9},
  "p-cottage-4-m-8": {n:"Cottage 4% M.G.E.S.", marca:"Daisy", cat:"lacteo", prod:true,
      medida:"1 pote (150 g)", u:["porcion","g"], gr:{porcion:150}, def:{u:"porcion",c:1},
      com:["desayuno", "merienda", "cena"],
      kcal:100, prot:11.3, carb:4.7, gras:4, fib:null, na:346, ca:null, fe:null, k:null, vc:null, sat:2.7, azu:4.7},
  "p-crema-de-leche-9": {n:"Crema de leche natural", marca:"Surlat", cat:"lacteo", prod:true,
      medida:"2 cucharadas (15 ml)", u:["porcion","g"], gr:{porcion:15}, def:{u:"porcion",c:1},
      com:["comida", "cena"],
      kcal:314, prot:3.3, carb:3.4, gras:33, fib:null, na:31, ca:null, fe:null, k:null, vc:null, sat:21, azu:3.1},
  "p-crema-de-leche-10": {n:"Crema de leche", marca:"Nestlé", cat:"lacteo", prod:true,
      medida:"2 cucharadas (25 g)", u:["porcion","g"], gr:{porcion:25}, def:{u:"porcion",c:1},
      com:["comida", "cena"],
      kcal:233, prot:2.5, carb:3.9, gras:23, fib:null, na:35, ca:null, fe:null, k:null, vc:null, sat:14.3, azu:3.3},
  "p-pure-passata-de-11": {n:"Pure Passata de tomate", marca:"La Molisana", cat:"verdura", prod:true,
      medida:"3 cucharadas (aprox. 60 g)", u:["porcion","g"], gr:{porcion:60}, def:{u:"porcion",c:1},
      com:["comida", "cena"],
      kcal:23, prot:1.3, carb:3.6, gras:0, fib:null, na:156, ca:null, fe:null, k:null, vc:null, sat:null, azu:3.6},
  "p-atun-lomitos-en-12": {n:"Atún lomitos en agua", marca:"Robinson Crusoe", cat:"proteina", prod:true,
      medida:"46 g (1/2 lata, peso drenado)", u:["porcion","g"], gr:{porcion:46}, def:{u:"porcion",c:1},
      com:["comida", "cena"],
      kcal:101, prot:25, carb:0, gras:0.32, fib:null, na:295, ca:null, fe:null, k:null, vc:null, sat:0.13, azu:0},
  "p-sardinas-en-aceite-13": {n:"Sardinas en aceite de oliva", marca:"Vigilante", cat:"proteina", prod:true,
      medida:"1/4 taza (60 g)", u:["porcion","g"], gr:{porcion:60}, def:{u:"porcion",c:1},
      com:["comida", "cena"],
      kcal:265, prot:19, carb:0, gras:21, fib:null, na:270, ca:null, fe:null, k:null, vc:null, sat:4.3, azu:0},
  "p-porotos-negros-sin-14": {n:"Porotos negros sin sal añadida", marca:"IANSA Agro", cat:"legumbre", prod:true,
      medida:"1/2 envase (195 g)", u:["porcion","g"], gr:{porcion:195}, def:{u:"porcion",c:1},
      com:["comida"],
      kcal:59, prot:5, carb:8.8, gras:0.4, fib:5.5, na:7.3, ca:null, fe:null, k:null, vc:null, sat:0.1, azu:0.5},
  "p-garbanzos-15": {n:"Garbanzos", marca:"Wasil", cat:"legumbre", prod:true,
      medida:"1/2 envase (190 g)", u:["porcion","g"], gr:{porcion:190}, def:{u:"porcion",c:1},
      com:["comida"],
      kcal:100, prot:5.9, carb:14.1, gras:2.2, fib:null, na:210, ca:null, fe:null, k:null, vc:null, sat:null, azu:1},
  "p-keto-granola-cacao-16": {n:"Keto Granola Cacao Powder", marca:"Andes Secret", cat:"cereal", prod:true,
      medida:"1/4 taza (30 g)", u:["porcion","g"], gr:{porcion:30}, def:{u:"porcion",c:1},
      com:["desayuno", "merienda"],
      kcal:549, prot:16, carb:8.22, gras:50.2, fib:7.31, na:134, ca:null, fe:null, k:null, vc:null, sat:18.8, azu:3.61},
  "p-pasta-de-mani-17": {n:"Pasta de maní natural 100% maní alto oleico", marca:"Maní King", cat:"grasa", prod:true,
      medida:"20 g (1 cucharada de sopa)", u:["porcion","g"], gr:{porcion:20}, def:{u:"porcion",c:1},
      com:["desayuno", "merienda"],
      kcal:586, prot:26, carb:10, gras:49, fib:9.2, na:0, ca:null, fe:null, k:null, vc:null, sat:6.4, azu:7.5},
  "p-pan-perfecto-integral-18": {n:"Pan Perfecto Integral bajo índice glicémico", marca:"Kingsbury", cat:"cereal", prod:true,
      medida:"2 rebanadas (48 g)", u:["porcion","g"], gr:{porcion:48}, def:{u:"porcion",c:1},
      com:["desayuno", "merienda", "cena"],
      kcal:188, prot:13, carb:29.7, gras:1.7, fib:null, na:373, ca:null, fe:null, k:null, vc:null, sat:0.3, azu:2.2},
  "p-aceitunas-negras-descarozadas-19": {n:"Aceitunas negras descarozadas", marca:"Don Juan", cat:"grasa", prod:true,
      medida:"5 unidades (14 g)", u:["porcion","g"], gr:{porcion:14}, def:{u:"porcion",c:1},
      com:["comida", "cena"],
      kcal:169, prot:1.2, carb:0.5, gras:18, fib:null, na:920, ca:null, fe:null, k:null, vc:null, sat:3, azu:0},
  "p-soy-sauce-all-20": {n:"Soy Sauce All-Purpose", marca:"Kikkoman", cat:"condimento", prod:true,
      medida:"15 ml (1 cucharada)", u:["porcion","g"], gr:{porcion:15}, def:{u:"porcion",c:1},
      com:["comida", "cena"],
      kcal:70, prot:10.3, carb:7.3, gras:0, fib:null, na:5668, ca:null, fe:null, k:null, vc:null, sat:null, azu:0.5},
  "p-aceite-de-oliva-21": {n:"Aceite de oliva extra virgen", marca:"Chef", cat:"grasa", prod:true,
      medida:"1 cdta. (5 ml)", u:["porcion","g"], gr:{porcion:5}, def:{u:"porcion",c:1},
      com:["comida", "cena"],
      kcal:828, prot:0, carb:0, gras:92, fib:null, na:0, ca:null, fe:null, k:null, vc:null, sat:16, azu:0},
  "p-spaghetti-n15-integral-22": {n:"Spaghetti N°15 integral Grano Decorticato a Pietra", marca:"La Molisana", cat:"cereal", prod:true,
      medida:"80 g", u:["porcion","g"], gr:{porcion:80}, def:{u:"porcion",c:1},
      com:["comida"],
      kcal:352.5, prot:15, carb:65, gras:2.5, fib:7.5, na:32.5, ca:null, fe:null, k:null, vc:null, sat:0, azu:null},
  "p-psyllium-husk-organico-23": {n:"Psyllium Husk orgánico en polvo", marca:"Manare", cat:"condimento", prod:true,
      medida:"1 cucharada (10 g)", u:["porcion","g"], gr:{porcion:10}, def:{u:"porcion",c:1},
      com:["desayuno", "comida"],
      kcal:214, prot:2.8, carb:4.1, gras:2.7, fib:81, na:58, ca:null, fe:null, k:null, vc:null, sat:null, azu:0},
  "p-hojas-de-arroz-24": {n:"Hojas de arroz / Rice Paper", marca:"Cock Brand", cat:"cereal", prod:true,
      medida:"55 g (8 unidades)", u:["porcion","g"], gr:{porcion:55}, def:{u:"porcion",c:1},
      com:["comida", "cena"],
      kcal:327, prot:3.6, carb:78, gras:0, fib:null, na:472, ca:null, fe:null, k:null, vc:null, sat:null, azu:0},
  "p-pan-rallado-artesanal-25": {n:"Pan rallado artesanal", marca:"Vollkorn", cat:"cereal", prod:true,
      medida:"3 cucharadas soperas (30 g)", u:["porcion","g"], gr:{porcion:30}, def:{u:"porcion",c:1},
      com:["comida", "cena"],
      kcal:357, prot:11.3, carb:71, gras:1.7, fib:null, na:520, ca:null, fe:null, k:null, vc:null, sat:null, azu:1},
  "p-gold-standard-100-26": {n:"Gold Standard 100% Whey - Vanilla Ice Cream", marca:"Optimum Nutrition", cat:"proteina", prod:true,
      medida:"1 medida dosificadora (31 g)", u:["porcion","g"], gr:{porcion:31}, def:{u:"porcion",c:1},
      com:["desayuno", "merienda"],
      kcal:387, prot:77, carb:8.7, gras:4.8, fib:null, na:419, ca:419, fe:null, k:null, vc:null, sat:3.2, azu:3.2}
};
